# Generated by Django 4.1.5 on 2023-03-02 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_quizattempt_question_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='points',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='User Score'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='total_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total Score'),
        ),
    ]
