# Generated by Django 4.1.5 on 2023-03-02 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_quiz_points_alter_quizresult_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='points',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Quiz Score'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='user_score',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='User Score'),
        ),
    ]
