# Generated by Django 4.1.5 on 2023-02-15 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_choices', to='contents.question', verbose_name='Questions'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_quiz_answer', to='contents.choices', verbose_name='User Choice'),
        ),
    ]
