# Generated by Django 4.1.5 on 2023-03-02 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='User Point'),
        ),
    ]
