# Generated by Django 4.1.5 on 2023-03-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_alter_user_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='User Point'),
        ),
    ]
